# Generated by Django 4.1.7 on 2023-03-13 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='admin_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctors',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='details_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctors',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctors',
            name='fees',
            field=models.PositiveIntegerField(default=399),
        ),
        migrations.AddField(
            model_name='doctors',
            name='first_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='doctors',
            name='hosp_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='doctors',
            name='img',
            field=models.ImageField(default=None, max_length=300, upload_to=None),
        ),
        migrations.AddField(
            model_name='doctors',
            name='last_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='doctors',
            name='qualification',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='doctors',
            name='slot_end',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='doctors',
            name='slot_start',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='doctors',
            name='speciality',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='doctors',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='details_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='img',
            field=models.ImageField(default=None, max_length=300, upload_to=None),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
