# Generated by Django 4.1.7 on 2023-03-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_doctors_admin_verified_doctors_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='img',
            field=models.ImageField(max_length=300, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='patient',
            name='img',
            field=models.ImageField(max_length=300, null=True, upload_to=None),
        ),
    ]
