# Generated by Django 4.1.7 on 2023-03-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_doctors_img_alter_patient_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
    ]
